export DATABASE_URL='URL'

export DISCORD_BOT_TOKEN="TOKEN"
export USER_PASSWORD="PASSWORD"
export ADMIN_PASSWORD="PASSWORD"
export SECRET_KEY=$(openssl rand -base64 32)

export ALGORITHM="HS256"
export ACCESS_TOKEN_EXPIRE_MINUTES="30"