export DATABASE_URL="URL"
export SECRET_KEY="KEY"

export DISCORD_BOT_TOKEN="TOKEN"
export USER_PASSWORD="PASSWORD"
export ROOT_PASSWORD="PASSWORD"

export ALGORITHM="HS256"
export ACCESS_TOKEN_EXPIRE_MINUTES="30"